### ISSUE TITLE
Non english symbols in uploaded file

### ISSUE THREAD

**Issue by xenolOnline** [dilab/resumable.php#1]
Hello, I fount that on some servers unable to load file with non english symbols in their names. I did changes in Resumable.php in method:
public function tmpChunkFilename($filename, $chunkNumber)
    {
        return md5($filename) . '.part' . $chunkNumber;
    }

**Comment by dilab** [comment]
Hi

Thanks for reporting the issue. 

We will fix that.

**Comment by dilab** [comment]
Decide to drop this change.

As keeping the original filename is reasonable. Non-english symbols should be solved from the server instead of this script.
