### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by DomDomDom13** [dilab/resumable.php#16]
Hi There,

I'm curious to what the front-end would look like to get this to work. Are there any examples?

Thanks

**Comment by adadgio** [comment]
Well, speaking for myself, i'm using [ResumableJS](http://resumablejs.com/), it integrates without a hitch !

**Comment by DomDomDom13** [comment]
Would you have an example of the front-end to share? That's what I'm trying to figure out. I want to try and integrate it with Laravel, so I'm not sure how to connect the two ends.

**Comment by dilab** [comment]
Agree with @adadgio 

You should use ResumbleJs , that is what this lib is made for.

Check out the tutorial.

**Comment by DomDomDom13** [comment]
Thanks both, I'll check out the tutorial and see what I end up with.

**Comment by adadgio** [comment]
I've posted raw code bellow (you'll need to adapt a lot of things , especially PHP folder upload pathes that come from my config and all). I'm using Symfony 2, @dilab 's Resumable PHP library of course, require JS modules (with my custom [melody-js](https://github.com/adadgio/melody-js - a require JS framework to work the Symfony way in javascript, check it its great! :p), and a quick easy HTML template (no CSS here, but i'm sure you can manager).

require JS controller
https://gist.github.com/adadgio/f6e343b19fd4a465400eca64e06fc991

require JS upload module
https://gist.github.com/adadgio/e40a5717b93b19ee511dafca56d8f554

HTML template
https://gist.github.com/adadgio/5ed5ed4d9fa778c93450487b3ba07c2e

PHP controller
https://gist.github.com/adadgio/165ac61d7727152dcf04c9d994dec0f7

Hopefully this issue can be closed now ! :-)

**Comment by dilab** [comment]
@adadgio Awesome man!

**Comment by DomDomDom13** [comment]
Thanks for the help both, appreciate it!
