### ISSUE TITLE
mkdir file exists

### ISSUE THREAD

**Issue by wyklif** [dilab/resumable.php#17]
this chunk of code on resumable.php at times fails with mkdir file exists please help

```
public function tmpChunkDir($identifier)
    {
        $tmpChunkDir = $this->tempFolder . DIRECTORY_SEPARATOR . $identifier;
        if (!file_exists($tmpChunkDir)) {
            mkdir($tmpChunkDir);
        }
        return $tmpChunkDir;
    }
```

**Comment by dilab** [comment]
is there any particular error message you can provide for us to debug?

**Comment by adadgio** [comment]
Hm, actually, the issue seems straight forward... `file_exists` > then `mkdir` ? Should be `is_dir` in my opinion ;-).

**Comment by dilab** [comment]
@adadgio 
Hmmm, I think file_exists does check directory.

> file_exists — Checks whether a file or directory exists

Refer to http://php.net/manual/en/function.file-exists.php

**Comment by adadgio** [comment]
My bad, you are absolutely right @dilab ! 

Other suggestion which happened to me quite a few times... the function would return false when the file permissions are wrong (or if the server does not have them).

See also the `warning` section of http://php.net/manual/en/function.file-exists.php

I think this is it. Try to fix your permissions.

**Comment by dilab** [comment]
I think it makes sense. 

We could throw an exception if ```file_exists``` return FALSE.

**Comment by adadgio** [comment]
Yup. Right thing to do i guess.

**Comment by wyklif** [comment]
this seemed to appear randomly it doesnt appear now however after deploying my code to a virtual machine i seem to get an error all of dillab backend methods dont work including Call to undefined method Dilab\Resumable::getExtension() 
however it works very wel on my local development environment
please assist

this is my code
```
$request = new SimpleRequest();
$response = new SimpleResponse();
$resumable = new Resumable($request, $response);
$ext = $resumable->getExtension();
```

**Comment by dilab** [comment]
@wyklif is the server working for your other PHP codes? What is the server and PHP specs?

**Comment by wyklif** [comment]
Yes the server is working before i first begin uploading i use intervention to get an uploaded image resize and save it that part is working fine so i am sure that composer autoload is working fine.. then the progress bar loads to the end then it fails with the above error. i am on ubuntu 14.04 on a lamp stack i ahve set upload file size to 5G post size to 5G maximum execution time to 3600 i am on php 5.6 im using laravel 5.3

**Comment by dilab** [comment]
Why are you calling ``` $ext = $resumable->getExtension(); ```  directly?

**Comment by wyklif** [comment]
because i am generating a random name for an uploaded file then appending its extension so that the file is served correctly

**Comment by AndriusCTR** [comment]
you should update tmpChunkDir to work with windows filesystem too (if dev pc has windows):

instead of

 `mkdir($tmpChunkDir);`

do

`mkdir($tmpChunkDir, 0777, true);`

Otherwise mkdir will throw errors about file missing, etc.

**Comment by dilab** [comment]
a PR is welcome.
