### ISSUE TITLE
headers and HTTP 1.1

### ISSUE THREAD

**Issue by AndriusCTR** [dilab/resumable.php#23]
I strongly recommend, that you use

`header($_SERVER["SERVER_PROTOCOL"]." 404 Not Found");`

instead of

`header("HTTP/1.0 404 Not Found"); `

Inside _SimpleResponse_ class.

Especially when we have HTTP/1.1 now everywhere...

**Comment by dilab** [comment]
a PR is welcome

**Comment by dilab** [comment]
fixed and thanks to @dedad0
