### ISSUE TITLE
upload video can not play

### ISSUE THREAD

**Issue by SumatJiang** [dilab/resumable.php#3]
Hi, i uploaded videos, the videos can not play

**Comment by dilab** [comment]
Did it upload successfully if you check from the server side?

What format and size of the video file?

**Comment by dilab** [comment]
Issue should be fixed with 0.1.2.

Issue was caused by `createFileFromChunks`, it does not combine chunks with correct order, applying `natsort` fixed the issue, thanks to @georaldc https://github.com/dilab/resumable.php/issues/2#issuecomment-164575724
