### ISSUE TITLE
Make Contribution

### ISSUE THREAD

**Issue by abilogos** [dilab/resumable.php#35]
Hi @dilab ,

first Thanks for the convenient library you have made for the PHP backend of resumable j.

I have used it in my legacy projects,
but this year I wanted to use it again I have found the monolog version I had was different with dilab/resumale.php then I have improved and fixed a bug ...

now, I am trying to update the unit test codes to be upgraded and work with the latest phpunit.

I think this library is great and I want to revive & fresh it though.

so I was wondering how can I share my contributions ?

just make a PR with all changes or one-PR-per-one-improvement ?

**Comment by dilab** [comment]
thanks for the contribution. PR merged!
