### ISSUE TITLE
Add ability to specify uploaded filename?

### ISSUE THREAD

**Issue by georaldc** [dilab/resumable.php#4]
Would it be reasonable to have a method to dictate what the uploaded file filename would be (instead of using the original filename)? I could probably come up with a PR if so

**Comment by dilab** [comment]
that sounds like a good idea. 

or the better, extract the naming method to a strategy, so we can swap in different strategies for naming the uploaded file.

**Comment by adadgio** [comment]
I have made a PR on that, its now in sync (dilabel there is a last one you need to pull which just includes a isUploadComplete public method and getExtension public method). We can close the issue ! :-)

**Comment by dilab** [comment]
@adadgio Will need you to fix the tests before I can merge.

**Comment by adadgio** [comment]
I've commited the fix (+README) but i'm not in the position to unit test right now. Does that fixes the issue ?

Tks

**Comment by georaldc** [comment]
Tests pass with the latest changes from @adadgio

**Comment by adadgio** [comment]
All lights green then : -). @dilab would you be so kind to make a new release when you merge ? Tks.

**Comment by dilab** [comment]
@adadgio @georaldc  awesome! merged and new tag created. 

thanks for the code. 

:)
