### ISSUE TITLE
[PR] Allow custom filename and automatic filename slugify

### ISSUE THREAD

**Issue by adadgio** [dilab/resumable.php#5]
I have enhanced the library to be able to set custom final filename (or slugify it) but i'm not able to make a pull-request. Could you allow those ?

Thanks ++
Romain

**Comment by dilab** [comment]
Hi Romain

Thanks for the efforts. 

I did not explicitly disallow PR, you should be able to do that.
Can you double check on your end?

**Comment by adadgio** [comment]
Its fine i've done it (forked and created pull request with stable version). You should see the PR now.

I've basically changed only a few stuff inside ::createFileAndDeleteTmp()

```
if (null !== $this->filename) {
            // optionaly create a unique slugified filename
            if ($this->filename === static::SLUGIFY) {
                $slugify = new Slugify();
                $filename = $slugify->slugify($filename);
            } else {
                // else use user define custom final file name
                $filename = $this->createSafeFilename($this->filename, $filename);
            }
        }
```

And then all the other stuff is just protected properties for filename and SLUGIFY constant.
Finally added a Slugify class (Helper/Slugify) inside the project.

All right ?

**Comment by dilab** [comment]
Merged. Thanks for the code!

**Comment by adadgio** [comment]
Great !
