### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by y-lohse** [dilab/resumable.php#8]
Hi,
I just installed this and gave it a test drive. A couple of things
- monolog is listed as a dev dependecy but is used within the code, so if it's not installed there is an error
- errors are generated when the temp and upload folders don't exist. I didn't expect to have to create a temp folder but whatever.
- once everyhting is setup, it works like a charm
- my main concern is that the `process` function is a total black box. From the outside, I have absolutely no way of telling what just happened (test request? new upload? resumed? end?)

Did I miss something? If not, do you have any plans to address this, or would you accept a patch adding this sort of features?

Cheers,
Yannick

**Comment by adadgio** [comment]
I agree about monolog, should be out of the deps.

On the last concern:  there is a PR on the way (2nd iteration) that added public methods to hook into some events like isUploadComplete, setFilename before / after upload, etc.

About the tmp and upload folder, seems quite normal although this could be a nice feature to create them on the fly (but then users would probably get directory permissions errors whereas here, they create the folders and think about giving obvious permissions).

The black box is slowly opening.... ;-)

**Comment by y-lohse** [comment]
i'm glad to hear that, I'll keep an eye open for changes :-)
