### ISSUE TITLE
Use of Monolog in __construct?

### ISSUE THREAD

**Issue by georaldcamposano** [dilab/resumable.php#9]
I just updated my resumable.php package and noticed all my upload code stopped working. Looks like you added monolog support a few months ago and your class is trying to instantiate the monolog class in the constructor method. Monolog is defined as a dev dependency in your package though so it won't pull in when other users want to use your package.

**Comment by dilab** [comment]
@georaldcamposano thanks for reporting.  would you like to contribute a PR?

**Comment by georaldc** [comment]
Done (didn't notice I was using my other account when I created the issue)

**Comment by dilab** [comment]
Merged. 

Thanks for the code.
